site_name: Wang Hailin

repo_url: https://github.com/haiiliin/haiiliin.github.io
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Tags: tags.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.top
    - search.share
    - search.suggest
    - toc.follow
    - toc.sticky

plugins:
  - blog:
      blog_dir: "."
      post_url_format: "{slug}"
  - tags:
      tags_file: tags.md
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiiliin
