site_name: Wang Hailin's Blog Website

repo_url: https://github.com/haiiliin/haiiliin.github.io
edit_uri: edit/main/docs

nav:
  - Home:
      - Blog: index.md
      - Tags: tags.md
  - Abaqus/Python: /abqpy/
  - Micromechanics: /micromechanical/
  - Soil-Structure Interface: /interface/

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.share
    - search.suggest
    - toc.follow
    - toc.sticky

plugins:
  - blog:
      blog_dir: "."
      blog_toc: true
      archive_toc: true
      categories_toc: true
      post_url_format: "{slug}"
      archive_date_format: MMMM yyyy
  - tags:
      tags_file: tags.md
  - search
  - git-revision-date-localized:
      type: timeago

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/haiiliin
